server: irc.libera.chat:+6697
nickname: beryllia
# optional
#username: beryllia
# optional
#realname: beryllia
password: beryllia:hunter2
channels: []
log: "#libera-klines"
# maximum kline rejections to store per k-line
rejects: 20

sasl:
  username: beryllia
  password: hunter3

oper:
  name: beryllia
  file: ~/oper.key
  pass: hunter4

database:
  user: jess
  name: beryllia
  # optional
  #pass: hunter5
  # optional
  #host: 127.0.0.1
